### ISSUE TITLE
Top center should move bossbar

### ISSUE THREAD

**Issue by Madis0** [BerdinskiyBear/armor-hud#1]
Could you please move the boss bar a bit down when the anchor is set to top center?

**Comment by BerdinskiyBear** [comment]
I tried something in f0276af002b0e4a7b8bf70e41db1834aba5adecc and it seems to work well. Do you think this looks good?

This is how it looks now.
![2021-01-28_21 57 13](https://user-images.githubusercontent.com/56161020/106159868-d4153080-61b7-11eb-9ade-6d9a24c616c7.png)
If any warning icon are shown, then bossbars are pushed even lower.
![2021-01-28_21 56 34](https://user-images.githubusercontent.com/56161020/106160352-51d93c00-61b8-11eb-827e-005120d9b625.png)
If warning icons are not allowed to bob then bossbars are not pushed as far.
![2021-01-28_21 56 53](https://user-images.githubusercontent.com/56161020/106160521-80571700-61b8-11eb-8e28-a13ae33e790c.png)

I also will try to do something similar for the status effect icons.

**Comment by Madis0** [comment]
Yes, that looks good!
