### ISSUE TITLE
1.19.4 version broken on servers

### ISSUE THREAD

**Issue by sebdnlp** [BerdinskiyBear/armor-hud#23]
the 1.19.4 version of BerdinskyBear's armour hud is broken on online servers like PvP Legacy and Tumbleweed. The mod works in singleplayer and on DonutSMP however. This is confusing.

**Comment by BerdinskiyBear** [comment]
Can you describe the issue in more detail? Describe what you expect to see and what you are actually seeing. If possible, attach screenshots of the issue. Also a screenshot of the issue with inventory open would be useful.

**Comment by sebdnlp** [comment]
![image](https://user-images.githubusercontent.com/130645024/231944773-79455808-9ed9-41cf-af8b-1636ea3f51c4.png)
![image](https://user-images.githubusercontent.com/130645024/231944827-0a583714-56fd-4711-9282-34e536a52c10.png)
As you can see in the first two images, it doesn't work on PvP Legacy, however on Donut SMP, it does shown in the following two images.
![image](https://user-images.githubusercontent.com/130645024/231945045-568ab44c-61dd-4f73-bf74-59e57c512944.png)
![image](https://user-images.githubusercontent.com/130645024/231945082-6a9a9a66-301c-4c10-a8eb-81707b21905b.png)

**Comment by BerdinskiyBear** [comment]
Have you checked if mod works while in game with armor equiped? Have you tried to change "Widget shown" option?

**Comment by BerdinskiyBear** [comment]
I can't check properly PvP Legacy since I have only RaspberryPi for pc and a touchpad for its input, but on Tumbleweed SMP mod seems to work.

![20230414_160316.jpg](https://user-images.githubusercontent.com/56161020/231998410-d1bc124b-bb74-437f-bed2-24b96f8997f7.jpg)
sorry for photo

**Comment by sebdnlp** [comment]
Sorry for the inconvenience, I managed to fix the problem.
