### ISSUE TITLE
Feature Request: Some pixels...

### ISSUE THREAD

**Issue by sternschnaube** [BerdinskiyBear/armor-hud#24]
Fantastic mod - all the options are rounded 🥳
I play with Arrows Info and noticed a small pixel difference... could you please add another style with a few more pixels? 😂
https://legacy.curseforge.com/minecraft/mc-mods/arrows-info

![image](https://user-images.githubusercontent.com/120551916/233231596-3c8b5f38-3b1e-41b0-aa44-7c7c9e0f531c.png)

**Comment by BerdinskiyBear** [comment]
It seems to be an issue with Arrows Info. Pixels in the corners of slot frame are supposed to be transparent. Also note that the slot's background is not translucent either. It seems that the color blending is not enabled before drawing the slot's background and frame. I think it is the cause of the difference of Arrows Info slot when compared to Minecraft's off-hand slot and ArmorHUD's widget.

This is how widget looks as it is
![2023-04-21_09 48 56-](https://user-images.githubusercontent.com/56161020/233531190-c7d70520-f3aa-4bf9-be2f-417e63edc712.png)

And this is how widget looks if I enable blending
![2023-04-21_09 47 50-](https://user-images.githubusercontent.com/56161020/233531202-0fef4951-8d18-4df3-957a-4cbb17a2f9e1.png)

Note that in the second screenshot one can see outline of acacia tree through the slot and there are no extra pixels at the corners of the slot frame.

I can report this issue to the Arrows Info.

**Comment by BerdinskiyBear** [comment]
I made a pull request for Arrows Info mod intact/arrows-info#4

**Comment by sternschnaube** [comment]
Thanks @BerdinskiyBear, he published the build with transparency fix 😊
